# Site settings
title:              Robotics Portfolio
email:              nolanknight133@icloud.com
description:        "Portfolio for Robotics at Northwestern University"
url:                "https://<username>.github.io"
baseurl:            "/nolanknight" #repo name

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

#Theme: 
theme: jekyll-theme-midnight

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
