# Site settings
title: Nolan Knight
description: My Professional Portfolio
url: "https://ncknight-un.github.io"
baseurl: ""   # user sites always have empty baseurl
theme: jekyll-theme-midnight

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
